spring:
   profiles:
     active:
      -dev
---
spring:
    profiles:dev
    application:
        name:springcloud-config-facemash-dev
---
spring:
    profiles:test
    application:
        name:springcloud-config-facemash-test